### ISSUE TITLE
compatibility with Telerik AppBuilder build services 

### ISSUE THREAD

**Issue by barsh** [nordnet/cordova-universal-links-plugin#10]
Telerik has a build service for cordova apps called AppBuilder.  Unfortunately, this plugin doesn't work with AppBuilder.

http://www.telerik.com/forums/ios-9-universal-links

**Comment by nikDemyankov** [comment]
The answer in the provided link is correct. Plugin uses hooks to generate proper configuration files for iOS and Android. When you execute `cordova build` (or `ionic build`) - it reads project's main `config.xml`, and inject's different preferences into android and ios projects. Those preferences activate support for Universal Links. So, if AppBuilder doesn't execute them - plugin wont work. I would say that this is an issues/feature request to the AppBuilder.
