### ISSUE TITLE
Issues when working with URL's containing special characters

### ISSUE THREAD

**Issue by iamchrisw** [nordnet/cordova-universal-links-plugin#100]
Hi All,

Has anybody ran into any issues when using special characters in URL's? I am attempting to put the following into the path url: */link?url=/Work/* does not appear to work at all where as */Work/Test/* does work fine.

Thanks

**Comment by nikDemyankov** [comment]
Hi,

Can you, please, share: 
- For what platform you are testing this?
- Which urls you are using? Which one is failing, and which one succeeds? Preferably the full one like `http://somedomain.com/some/path`.

**Comment by iamchrisw** [comment]
Hi,

I am testing this on iOS currently, the url's I am using are:

    <universal-links>
        <host name="xxx.com" >
            <path url="*/link?url=/MyPortal/Authenticate/*" event="openLink" />
            <path url="*/link?url=/MyPortal/Documents/*" event="openLink" />
            <path url="*/MyPortal/Authenticate/*" event="openLink" />
            <path url="*/MyPortal/Documents/*" event="openLink" />
        </host>
    </universal-links>

When I go to https://xxx.com/MyPortal/Authenticate/ or https://xxx.com/MyPortal/Documents/

Then it works as it should, but if i go to https://xxx.com/link?url=/MyPortal/Authenticate/ it doesn't appear to work.

Thanks,

**Comment by nikDemyankov** [comment]
Yes, it doesn't work. You can't use query parameters for url matching. They are ignored by the operating system.

**Comment by iamchrisw** [comment]
Is there any way around this? Or is this just something that I have to work around?

**Comment by nikDemyankov** [comment]
This story is similar to https://github.com/nordnet/cordova-universal-links-plugin/issues/86 . You can check it out.

In short - you can capture all links from your website by defining only `<host name="xxx.com"/>`, and then process paths with query params on the JS side to detect, which view to present to the user.
