### ISSUE TITLE
Phonegap build dont see the config.xml 

### ISSUE THREAD

**Issue by maugrejanin** [nordnet/cordova-universal-links-plugin#101]
Hi,

I put the UL tag in my config.xml :

```
<universal-links>    
    <host name="myapp.com" scheme="http" />  
</universal-links>
```

The local build for Android is always successful, and works fine, but when i make the phonegap build on the build.phonegap, i have no error and the plugin not works.

My cordova version is 6.5.0

Can you help me?

Thank you

**Comment by nikDemyankov** [comment]
Hi,

Currently plugin doesn't support PGB. You can check full discussion about that [here](https://github.com/nordnet/cordova-universal-links-plugin/issues/28).
