### ISSUE TITLE
Entitlement file missing aps-environment

### ISSUE THREAD

**Issue by pitAlex** [nordnet/cordova-universal-links-plugin#105]
I've installed this plugin, after install phonegap-plugin push and I noticed that the 'aps-environment' where not copied over the new Resources/.entitlements file. This causes a built error to happen in Xcode because thats the file used when building the package. Shouldn't this plugin copy existing keys of the original entitlements file over to the new ones since its setting the the project to use it??

**Comment by nikDemyankov** [comment]
Probably it relates to this issue: https://github.com/nordnet/cordova-universal-links-plugin/issues/89. But overall - this is a bug: it should work fine with push plugin.

**Comment by xavier-villelegier** [comment]
I can see many issues about that (like #8, #89 and #115), even a PR #151. Is there any chance to see this bug fixed soon ? 🤔
