### ISSUE TITLE
[Ask] Recommended way to distinguish app launch with and without universal link

### ISSUE THREAD

**Issue by olszowka-cargurus** [nordnet/cordova-universal-links-plugin#107]
My app needs to have two different behaviors depending upon whether it was launched as a result of clicking on a universal link or launched directly.  Currently, the _ondeviceready_ event handler creates the subscription to the _universallinks_ event and also sets a 10ms timeout for the default behavior to begin.  Furthermore, the _universallinks_ event handler sets a flag which prevents the default behavior.

My solution appears to work, but feels kludgy to me?  Is there a better practice?  If not, I'm willing to update the documentation to clarify.

**Comment by olszowka-cargurus** [comment]
Follow up:
The 10ms delay worked fine on an Android phone, but wasn't long enough on iOS.  I upped it to 75 ms and then it worked on iOS.  I would prefer a solution which didn't depend on any racing, e.g. a flag which could be tested in _ondeviceready_ to immediately determine whether the app was launched using a universal link or directly.

**Comment by eg271** [comment]
I also have the same situation.  Any answer on this?

**Comment by olszowka-cargurus** [comment]
I have heard nothing.

We decided to stop using universal links, anyway, so I haven't been pursuing it.

  --PeterO
