### ISSUE TITLE
Works when app compiled from X-Code but not from command line

### ISSUE THREAD

**Issue by darkyen** [nordnet/cordova-universal-links-plugin#108]
The deeplinks work if and only if I manually run the app from Xcode and not from the cordova command line. Help!?

**Comment by AresDev** [comment]
I have the same problem...

from: https://github.com/driftyco/ionic-plugin-deeplinks/issues/97

I'm working on an app that uses deep links and everything works just fine when I build and run the app from XCode but when I run it using ionic run ios --device it doesn't work and in consequence, our builds generated from CI and uploaded to Hockey App have the same behavior.

I've created an app from the ground up, added the plugin and platform and it behaves the same.

Did you find any solution to this?

**Comment by darkyen** [comment]
nope

**Comment by haiquangtran** [comment]
See https://github.com/nordnet/cordova-universal-links-plugin/issues/115.
