### ISSUE TITLE
Works on Android but not iOS

### ISSUE THREAD

**Issue by GregBath22** [nordnet/cordova-universal-links-plugin#109]
I have followed all the setup procedure as described but any link to the domain of my app opens in safari currently

only host one host which is a wild card = "*.domain.net" to catch links to both our mobile and desktop site.

This works out of the box for android but not iOS.

Any advice?

**Comment by washowasho** [comment]
Same here.

**Comment by pe1o2pl** [comment]
The same problem, on Android works fine, but doesn't on IOS, i have uploaded `apple-app-site-association` and validated it, set Associated domains in XCode and still can't open the app from the urls

**Comment by AltruistEnterprises** [comment]
Same problem here. 

When I test my url using The Apple  app search validation tool (https://search.developer.apple.com/appsearch-validation-tool/) it says "Could not extract required information for Universal Links.  Error: no apps with domain entitlements
_**The entitlement data used to verify deep link dual authentication is from the current released version of your app.**_" Does this mean we have to publish an app before being able to test if the iOS universal links are working?

**Comment by MattiaPrimavera** [comment]
+1

**Comment by newuser44** [comment]
I don't know if this is the same thing.  I just pushed out a deep link for our ios app.  A user updated the app and tried the link through an email.  Didn't work.  The user uninstalled and reinstalled.   Clicked the same link and it worked.  

Is there any bug with deep link on ios update?  Or does deep linking already have to be reinstalled?
