### ISSUE TITLE
Universal Link Not Working from Web Page

### ISSUE THREAD

**Issue by pvoelker** [nordnet/cordova-universal-links-plugin#11]
I am able to get my universal link to fire using ADB.  But I can't get it to fire from a web page using a link in the header.  I've confirmed that I am using the generated link under 'ul_web_hooks'.  Is there something that I am missing?  If I go to the page I would expect the a prompt to ask if I want to pull up my app or automatically be forwarded to my app.

I am using Android 5.1.1 on a Nexus 7 (2013).

I've seen some recent information that indicates Google has clamped down on deep links.

http://blog.tapstream.com/google-changes-chrome-to-prevent-abusive/
http://blog.tapstream.com/why-has-google-broken-deeplinking-on-android/#comment-1906522285

Is anyone else having this issue?  I am fairly new to Cordova.  So please pardon my ignorance...  Thanks

**Comment by nikDemyankov** [comment]
Try to do, as in [this tutorial](https://realm.io/news/juan-gomez-android-app-indexing/) , section `App Indexing`. You website need to be indexed, and app too. For that you need to verify your website in the Search Console and associate it with the app in the Google Play Console.

From the provided tutorial those steps are `3` and `4`:

> **Verify your website on Webmaster Tools**
> If your website is brand new, you’ll want to verify your site through Webmaster Tools. That’s how the Google crawler knows that it’s there and can index it to do everything it needs to do. In the Google Webmaster Tools, just send a verification request message (example: “Google Play: Link http://www.yourwebsite.com to Android application com.yourpackage.name”), then review and approve the information in the dialog.
> 
> **Connect your app using Google Play Console**
> Next, you’ll want to connect your app using the Google Play Console so the app indexing starts working. If you go to your app, there’s a menu that says “Services and API” in which you can click “Verify Website”, and provide the URL to check that it has the appropriate tags in the HTML. Once that’s all set up, it will start showing in search results.

I should have add that info in the readme, my bad, sorry.

**Comment by nikDemyankov** [comment]
Also, maybe this will be helpful: https://developers.google.com/app-indexing/android/publish#host-your-links
