### ISSUE TITLE
Error: Cannot find module '../plugman/platforms/ios'. Deprecated code in xcodePreferences.js after upgrading to Cordova 7.0.0

### ISSUE THREAD

**Issue by MarsupiL** [nordnet/cordova-universal-links-plugin#110]
See https://github.com/driftyco/ionic-plugin-deeplinks/issues/99
The fix suggested by peterpeterparker seems to work but a more permanent solution with a plugin update would be appreciated. 
Thanks for the support.

**Comment by lovelyelfpop** [comment]
function loadProjectFile() {
    var platform_ios;
    var projectFile;
    
    try {
        // try pre-5.0 cordova structure
        platform_ios = context.requireCordovaModule('cordova-lib/src/plugman/platforms')['ios'];
        projectFile = platform_ios.parseProjectFile(iosPlatformPath());
    } catch (e) {
        try {
            // let's try cordova 5.0 structure
            platform_ios = context.requireCordovaModule('cordova-lib/src/plugman/platforms/ios');
            projectFile = platform_ios.parseProjectFile(iosPlatformPath());
        } catch (e) {
            // Then cordova 7.0
            var project_files = context.requireCordovaModule('glob').sync(path.join(iosPlatformPath(), '*.xcodeproj', 'project.pbxproj'));
            
            if (project_files.length === 0) {
                throw new Error('does not appear to be an xcode project (no xcode project file)');
            }
            
            var pbxPath = project_files[0];
            
            var xcodeproj = context.requireCordovaModule('xcode').project(pbxPath);
            xcodeproj.parseSync();
            
            projectFile = {
                'xcode': xcodeproj,
                write: function () {
                    var fs = context.requireCordovaModule('fs');
                    
                var frameworks_file = path.join(iosPlatformPath(), 'frameworks.json');
                var frameworks = {};
                try {
                    frameworks = context.requireCordovaModule(frameworks_file);
                } catch (e) { }
                
                fs.writeFileSync(pbxPath, xcodeproj.writeSync());
                    if (Object.keys(frameworks).length === 0){
                        // If there is no framework references remain in the project, just remove this file
                        context.requireCordovaModule('shelljs').rm('-rf', frameworks_file);
                        return;
                    }
                    fs.writeFileSync(frameworks_file, JSON.stringify(this.frameworks, null, 4));
                }
            };
        }
    }
    
    return projectFile;
    }

**Comment by meermedia** [comment]
@lovelyelfpop 's solution worked for me, thank you!

**Comment by mikegleasonjr** [comment]
May I suggest the title contains at least the error encountered: `Error: Cannot find module '../plugman/platforms/ios'`. I found driftyco/ionic-plugin-deeplinks#99 before this one, even though I search the issue here first.

**Comment by alexnu** [comment]
Hi, this fix works as a temporary solution but is it going to be fixed on npm too ?

**Comment by mikegleasonjr** [comment]
Still not fixed, this is quite a pain to edit this function every time I install dependencies

**Comment by hrangel** [comment]
Can this be merged?

**Comment by velochy** [comment]
Why has this not been merged in 2 months? Is there a good reason?

**Comment by jespertheend** [comment]
Any updates on this?

**Comment by mikegleasonjr** [comment]
Hellooooooo? there are even forks that have the fix: https://github.com/flipflopapp/cordova-universal-links-plugin

**Comment by gvsrepins** [comment]
Hy guys, any plans to update it?
Or should we use the fork already?

**Comment by jespertheend** [comment]
The latest commit was on January 29th and there doesn't seem to be much activity from @nikDemyankov so I've got the feeling this repository has been abandoned.

**Comment by florgb02** [comment]
I am having same issues, merging with the unstable version of the plugin fixed it. Is there any plans on merging this?

**Comment by florgb02** [comment]
Any Plans on merging this fix?

**Comment by santiDotIO** [comment]
Any chance this will get merged soon?

**Comment by cloudmanic** [comment]
It would be amazing if this could get merged soon. Thanks!

**Comment by jespertheend** [comment]
This repository appears to be abandoned so your best option is to just use one of the forks mentioned in this thread.

**Comment by elgindavis** [comment]
I had the same issue with cordova 8.0 and was able to resolve this by reverting to cordova@6.5 --`npm i cordova@6.5`

**Comment by caleb87** [comment]
The code provided by lovelyelfpop throws an error when returning from a webview out of the app ("Return to App name..." in top-left) . 

`InvalidCharacterError: The string contains invalid characters.`

Any idea how to fix?

**Comment by travisdahl** [comment]
Also curious when an official fix will be merged...
Official firebase docs reference this plugin as a dependency, le sigh.
https://firebase.google.com/docs/auth/web/cordova
