### ISSUE TITLE
Can't subscribe event 

### ISSUE THREAD

**Issue by Aquanode** [nordnet/cordova-universal-links-plugin#119]
Hi,
I followed all the instructions to setup the universal links, the app is opening from a link but the event `reset-password` isn't working so App.resetPassword is never call.

```
onDeviceReady: function()
	{
		universalLinks.subscribe('reset-password', App.resetPassword);
 
	},
```
config.xml
```
    <universal-links>
        <host name="domain.ca" scheme="https">
            <path event="reset-password" url="/password/reset/*" />
        </host>
    </universal-links>
```
Any ideas??
Thanks

**Comment by tobischulz** [comment]
same here

**Comment by AltruistEnterprises** [comment]
I am having the same issue. 
Did either of you find a solution? 
Is there any way the trigger the event with javascript from the console for debugging?
