### ISSUE TITLE
Not working with PhoneGap Build for Android?

### ISSUE THREAD

**Issue by blukis** [nordnet/cordova-universal-links-plugin#124]
I cannot get this plugin to work using PhoneGap Build for Android.  The discussion in [this open issue relating to iOS](https://github.com/nordnet/cordova-universal-links-plugin/issues/28) seems to indicate getting it working for Android might be less problematic than for iOS.  Since that question & discussion related specifically to iOS, opening a new issue/question here for Android.

Is there a PGB workaround that works for Android?

(There's some discussion in the above issue about altering the AndroidManifest.xml using Cordova/PGB `<config-file>` tags, but I'm not sure what actually needs to be changed there for this plugin to work.)

**Comment by blukis** [comment]
OK, after (finally!) getting local cordova working to compare, and some trial-and-error, I can get this plugin partly working with PhoneGap Build with these additions to the config.xml:

```
<config-file platform="android" parent="/manifest/application" mode="merge">
	<activity android:launchMode="singleTask" />
</config-file>

<config-file platform="android" target="AndroidManifest.xml" parent="/manifest/application/activity[1]" mode="add">
	<intent-filter android:autoVerify="true">
		<action android:name="android.intent.action.VIEW" />
		<category android:name="android.intent.category.DEFAULT" />
		<category android:name="android.intent.category.BROWSABLE" />
		<data android:scheme="https" android:host="MYDOMAINHERE" android:path="/MYPATHHERE" />
	</intent-filter>
	<intent-filter android:autoVerify="true">
		<action android:name="android.intent.action.VIEW" />
		<category android:name="android.intent.category.DEFAULT" />
		<category android:name="android.intent.category.BROWSABLE" />
		<data android:scheme="https" android:host="OTHERDOMAINHERE"/>
	</intent-filter>
</config-file>
```

However, while links now trigger the app to open, the universalLinks.subscribe() callback doesn't seem to fire (neither with the default event, or with custom events).  (As was mentioned already [here](https://github.com/nordnet/cordova-universal-links-plugin/issues/28#issuecomment-253284377), we need a way to tell the plugin about which events to fire, and PGB apparently strips the <universal-links> tag from the config.xml.)

@nikDemyankov - you mentioned a "ul.json" type solution in [issue 28](https://github.com/nordnet/cordova-universal-links-plugin/issues/28#issuecomment-277203240).  Is this something that is implemented for Android, or could be?

**Comment by ghost** [comment]
Any luck with this @blukis ?

**Comment by blukis** [comment]
Nope.  I'm hoping someone smarter than me can help fill in there gaps I left above.  :)

I think the "ul.json" type solution discussed in the other issue would do the trick, but was unclear from that discussion whether that was ever implemented for Android.  (Looks like they were trying it in iOS, then ran into some iOS-specific showstoppers?)
