### ISSUE TITLE
www.example.com vs example.com

### ISSUE THREAD

**Issue by newuser44** [nordnet/cordova-universal-links-plugin#128]
I'm trying to figure out if I should be using **www** in front of my domain. 
I can only get to my site if I have www. in front.   without www its 404. 
So I assume in my config.xml file.  I need the host name = "**www**.example.com"

The two changes I see are:
In the android link file, it now has www.example.com

In the xcode Associated Domains  it now has applinks:www.example.com    I would think is what is wanted.

**Comment by jacquesdev** [comment]
Sounds right, I had the same issue.
