### ISSUE TITLE
Error when trying to add plugin

### ISSUE THREAD

**Issue by uerceg** [nordnet/cordova-universal-links-plugin#13]
Hi. I am trying to add `cordova-universal-links-plugin` to my app and I am getting following error:

```
uerceg:CordovaDemo uerceg$ cordova plugin add cordova-universal-links-plugin
Fetching plugin "cordova-universal-links-plugin" via npm
npm http GET https://registry.npmjs.org/cordova-universal-links-plugin
npm http 401 https://registry.npmjs.org/cordova-universal-links-plugin
TypeError: Cannot read property 'latest' of undefined
    at next (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache.js:687:35)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache.js:675:5
    at saved (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Any ideas how to add the plugin?

For the record, I am using Cordova version `5.1.1`.

Thanks in advance.

**Comment by nikDemyankov** [comment]
Just tried to install it by executing `cordova plugin add cordova-universal-links-plugin` and it worked. 

Maybe some issues with the npm? What version you are using? Also, can be because of your proxy server, if there is any.

**Comment by uerceg** [comment]
Yeah, it's probably because of that. I'll try to solve it and let you know. But directly from github, I managed to install it.

**Comment by nikDemyankov** [comment]
That is good)

**Comment by uerceg** [comment]
`npm` update did the trick. Thanks and sorry for false alarm.

**Comment by nikDemyankov** [comment]
Glad to hear that)
