### ISSUE TITLE
Failed to fetch plugin

### ISSUE THREAD

**Issue by mrneiverth** [nordnet/cordova-universal-links-plugin#130]
Hello, I'm new with Ionic and a got this error while trying to install plugin.

`cordova plugin add cordova-universal-links-plugin
Error: Failed to fetch plugin git+https://github.com/aramando/cordova-universal-links-plugin.git#35b3ed7e9a0310b12f1ac92a5159b21ce50eee57 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module`

Does anyone now what is happening ? (is not a connection problem)

> q@q-HP-Pavilion-14-Notebook-PC: node -v
v8.9.1
q@q-HP-Pavilion-14-Notebook-PC: npm -v
co5.5.1
q@q-HP-Pavilion-14-Notebook-PC: cordova -v
7.1.0
q@q-HP-Pavilion-14-Notebook-PC: ionic -v
3.19.0

**Comment by AltruistEnterprises** [comment]
What version of cordova are you using? 

I just encountered the same problem. After updating cordova from version 7.1 to version 8.0 the plugin installed without issues.

**Comment by mrneiverth** [comment]
I don't remember anymore, i guess that I solved it installing the plugin almost on hand. Anyway, closing it
