### ISSUE TITLE
Error: Cannot find module '../plugman/platforms/ios' - Cordova 7.1.0

### ISSUE THREAD

**Issue by Macario** [nordnet/cordova-universal-links-plugin#131]
Hi. I'm trying to use universal links plugin on iOS but when I install it, I can't add iOS platform and a get the error: Error: Cannot find module '../plugman/platforms/ios'

Cordova version: 7.1.0
cordova-ios version: 4.5.4
cordorva-universal-links-plugin version: 1.2.1
xCode 9

**Comment by hsunny110** [comment]
I got same message, Cannot find module '../plugman/platforms/ios'

Cordova version: 8.0.0
cordova-ios version: 4.5.4
cordorva-universal-links-plugin version: 1.2.1
xCode 9

**Comment by maxigarciaf** [comment]
I'm having the same issue? Anyone can solved it?

Cordova version: 7.1.0
cordorva-universal-links-plugin version: 1.2.1

**Comment by jfbourne** [comment]
One more here with the same issue

**Comment by valentinvoilean** [comment]
Check this: https://github.com/nordnet/cordova-universal-links-plugin/issues/110

I used the fork from this comment: https://github.com/nordnet/cordova-universal-links-plugin/issues/110#issuecomment-341081738

**Comment by AltruistEnterprises** [comment]
Same issue here. 

cordova-universal-links-plugin version 1.2.1
cordova v8.0.0
ios v4.5.4

**Comment by scchess** [comment]
Me too.

**Comment by pgcan** [comment]
i am also getting same issue

cordova-universal-links-plugin version 1.2.1
cordova v8.0.0
ios v4.2.0

**Comment by allanevargas** [comment]
In <project_folder>\plugins\cordova-universal-links-plugin\hooks\lib\ios\xcodePreferences.js

Change line 135-150:
```
function loadProjectFile() {
  var platform_ios;
  var projectFile;

  try {
    // try pre-5.0 cordova structure
    platform_ios = context.requireCordovaModule('cordova-lib/src/plugman/platforms')['ios'];
    projectFile = platform_ios.parseProjectFile(iosPlatformPath());
  } catch (e) {
    // let's try cordova 5.0 structure
    platform_ios = context.requireCordovaModule('cordova-lib/src/plugman/platforms/ios');
    projectFile = platform_ios.parseProjectFile(iosPlatformPath());
  }

  return projectFile;
}
```
To this:
```
function loadProjectFile() {
  var platform_ios;
  var projectFile;
  try {
    // try pre-5.0 cordova structure
    platform_ios = context.requireCordovaModule('cordova-lib/src/plugman/platforms')['ios'];
    projectFile = platform_ios.parseProjectFile(iosPlatformPath());
  } catch (e) {
    try {
      // let's try cordova 5.0 structure
      platform_ios = context.requireCordovaModule('cordova-lib/src/plugman/platforms/ios');
      projectFile = platform_ios.parse(iosPlatformPath());
    } catch (e) {
      // try cordova 7.0 structure
      var iosPlatformApi = require(path.join(iosPlatformPath(), '/cordova/Api'));
      var projectFileApi = require(path.join(iosPlatformPath(), '/cordova/lib/projectFile.js'));
      var locations = (new iosPlatformApi()).locations;
      projectFile = projectFileApi.parse(locations);
    }
  }
  return projectFile;
}
```

**Comment by Aarbel** [comment]
Have you found a solution ? Thanks !

**Comment by DanielGibbsNZ** [comment]
@Aarbel The solution that @aecvargas posted above worked for me.
