### ISSUE TITLE
Cannot read property 'manifest' of undefined

### ISSUE THREAD

**Issue by markovchainmontecarlo** [nordnet/cordova-universal-links-plugin#133]
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"

>cordova build
Android Studio project detected
(node:21980) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'manifest' of undefined
(node:21980) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

>cordova platform version android
Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

>cordova --version
8.0.0

>npm --version
5.6.0

>node --version
v8.9.3

**Comment by helenoalves** [comment]
Hello Folks !
This issue is open yet !?

There is an workaround for this error ?
I have exactly the same environment configuration as @jeremyspatrick !

@walteram Your fix worked to me too ! Thanks !

**Comment by okaufmann** [comment]
Is there any workaround till this get merged ?

**Comment by helenoalves** [comment]
@okaufmann look at the change of @walteram.
It worked to me, only changing the path to store manifest.

**Comment by okaufmann** [comment]
Do I need to use his version of this plugin or move the AndroidManifest.xml file to the old path? I'm confused...

**Comment by walteram** [comment]
@okaufmann you can use the changed version of the plugin. since it's not merged in the nordnet repository, you must remove the plugin and install again using: 
cordova plugin add https://github.com/walteram/cordova-universal-links-plugin

**Comment by hiepxanh** [comment]
@walteram why dont you make a pull request?   your code  is working! Thank you! you save my life ❤️

**Comment by fonsecas72** [comment]
thanks @walteram :+1:

**Comment by brnosouza** [comment]
I changed a bit @walteram pull request to be backward compatible

**Comment by rtm** [comment]
Can this be merged at some point in the future, or an equivalent change made in the main branch, or is there some other plan? It's a little unsettling to have to be using a third party's fork.

**Comment by abagusw** [comment]
Node version: v8.11.2
Cordova version: 8.0.0
Android version: 8.0
I Still got this. "UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'manifest' of undefined"

**Comment by lougreenwood** [comment]
Any news? Looks like a new release just needs cutting?

**Comment by skynixukraine** [comment]
It still does not work nor iOS nor Android

**Comment by monckey100** [comment]
This update needs to be pushed, I was adding the plugin and literally ran into it, seems like bad support that new users will just face this issue right off the bat and then have to resort to a third party branch.

**Comment by HarelM** [comment]
Same here, added the plug-in and bam, can't run my app. This is a showstopper guys...
