### ISSUE TITLE
iOS ERROR ITMS-90046 Code Signing Entitlements not supported on iOS. value 'app links:*my_domain.com' for key 'com.apple.developer.associated-domains'

### ISSUE THREAD

**Issue by AltruistEnterprises** [nordnet/cordova-universal-links-plugin#137]
When I try to upload my app to test flight after adding this plugin I am getting `ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'app links:*my_domain.com' for key 'com.apple.developer.associated-domains' in 'Payload/my_app.app/my_app' is not supported."`

I have enabled Associated Domains for my bundle id on developer.apple.com and the correct Associated Domains are showing up in the Capabilities tab in Xcode. 

What should I look for to resolve this?

**Comment by PaolinoD** [comment]
Hi,

seems like something in the actual value is wrong.

Try with `app links:*.my_domain.com`

--p

**Comment by AltruistEnterprises** [comment]
Thanks for your help @PaolinoD, 
After changing the value as you said and deleting and regenerating all my Xcode certificates I eventually got it to build and upload. However my universal links still don't seem to be working at all in iOS...

**Comment by GitFr33** [comment]
1.

**Comment by davidhedelin1** [comment]
Change this in Entitlements.plist:

> <key>aps-environment</key>
> <string>development</string>

To this:

> <key>aps-environment</key>
> <string>production</string>
