### ISSUE TITLE
Add additional maintainers

### ISSUE THREAD

**Issue by sandstrom** [nordnet/cordova-universal-links-plugin#141]
@nikDemyankov This is an awesome plugin! 

Have you considered adding more maintainers (write access)? That way, you could get help reviewing PRs etc.

(I know it's possible to fork, but for open-source projects to be successful work should be concentrated on a single repo)

**Comment by lougreenwood** [comment]
Looks like @nikDemyankov has abandoned the repro (and Cordova?) in favour of React Native..

Asking for new maintainers to be added is probably a lost cause... likely we need to see some fork emerge as the new canonical version
