### ISSUE TITLE
eventData contains at most 1 URL parameter

### ISSUE THREAD

**Issue by RikdeBoer** [nordnet/cordova-universal-links-plugin#144]
Hello

Thanks for this awesome plugin and superior documentation.

I have everything working beautifully in both Android and iOS.

Only one tiny thing, for if you have time, one rainy day. It appears that the ampersand symbol, i.e. &, to string together multiple query parameters, is not supported on the URL.

http://example.com?par1=val2 returns in the eventData of the callback the par1 and val1, but http://example.com?par1=val1&par2=val2 does not return par2 and val2.

**Comment by zmoshansky** [comment]
Just FYI:  I have been able to successfully get multiple params off a universal link on v1.2.1 (Tested days ago). `event.params.par1` && `event.params.par2`.

**Comment by RikdeBoer** [comment]
I use v1.2.1 too.
Maybe I should add that my experience is based on the "adb shell" tool, as mentioned in the documentation of this plugin.

Using adb I do not see multiple parameter values come into the eventData of the callback.
