### ISSUE TITLE
[Cordova] Can't use authentication engine from Firebase

### ISSUE THREAD

**Issue by namlunthkl** [nordnet/cordova-universal-links-plugin#150]
I'm developing apps using Cordova and I've just started using Firebase services for about 1 week and I'm stucking when trying to add Authentication into my Project. I don't know why but I've followed as the references said what I have to do: https://firebase.google.com/docs/auth/web/cordova
But I can't make the app redirect to the authentication URL, it doesn't redirect at any time.
Here is the config file:
`<?xml version='1.0' encoding='utf-8'?>
<widget id="com.nstudio.sentry" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>sentry</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
        <preference name="AndroidLaunchMode" value="singleTask" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <universal-links>
        <host name="z55t5.app.goo.gl" scheme="https" />
        <host name="sentry-58241.firebaseapp.com" scheme="https">
            <path url="/__/auth/callback" />
        </host>
    </universal-links>
    <plugin name="cordova-plugin-buildinfo" spec="^2.0.1" />
    <plugin name="cordova-plugin-browsertab" spec="^0.2.0" />
    <plugin name="cordova-plugin-inappbrowser" spec="^3.0.0" />
    <plugin name="cordova-plugin-customurlscheme" spec="^4.3.0">
        <variable name="URL_SCHEME" value="com.nstudio.sentry" />
    </plugin>
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-universal-links-plugin" spec="https://github.com/walteram/cordova-universal-links-plugin" />
</widget>`

And here is the Authenticate Script:
`// Initialize Firebase
var config = {
	apiKey: "XXXXXXXXX-TQ-gcqN7QEUfGv6Wzlzg4H6t1k4F_U",
	authDomain: "sentry-58241.firebaseapp.com",
	databaseURL: "https://sentry-58241.firebaseio.com",
	projectId: "sentry-58241",
	storageBucket: "sentry-58241.appspot.com",
	messagingSenderId: "14137267200"
};
firebase.initializeApp(config);
var provider = new firebase.auth.GoogleAuthProvider();
firebase.auth().signInWithRedirect(provider).then(function() {
	return firebase.auth().getRedirectResult();
}).then(function(result) {
	var token = result.credential.accessToken;
	var user = result.user;
}).catch(function(error) {
	var errorCode = error.code;
	var errorMessage = error.message;
});`

I've tested them both on my Emulator and my Android devices but there's no luck for me :( Anyone can help me with this?

**Comment by ImAnAutie** [comment]
It seems to be a known issue with this plugin and Phonegap Build.
(im also having this issue :( )

**Comment by PetersonRyan** [comment]
Any fix for this yet? I haven't been able to find anything.

**Comment by namlunthkl** [comment]
There's no solution for this case...
