### ISSUE TITLE
Event not firing if app first open

### ISSUE THREAD

**Issue by giugrilli** [nordnet/cordova-universal-links-plugin#23]
In my tests, following literally the guide, the event does not fire when the app is completely closed.

What I mean is that if the app is still running in in the foreground or in the background, the event is fired normally, and the url is handled by my javascript, showing the expected page.

However, if i kill the app, and run the same test command, the app gets opened, but no event is fired!

I am using latest Cordova and latest Ionic. Any hints?

**Comment by nikDemyankov** [comment]
As I understand, you are testing Android, Ionic. Then most likely there is a problem with the timing, where you subscribing for the event. The problem will go away when I'll finish with the https://github.com/nordnet/cordova-universal-links-plugin/issues/18.

But for now try to look into https://github.com/nordnet/cordova-universal-links-plugin/issues/21 and https://github.com/nordnet/cordova-universal-links-plugin/issues/15 . Those issues are similar to yours, maybe examples from there will help you.

**Comment by nikDemyankov** [comment]
Released new version with JS module, through which you need to subscribe for events. Please, check the docs. Particularly, [Application launch handling](https://github.com/nordnet/cordova-universal-links-plugin#application-launch-handling) section.
