### ISSUE TITLE
Multiple wildcard in url is broken

### ISSUE THREAD

**Issue by tdelmas** [nordnet/cordova-universal-links-plugin#26]
According to the documentation https://github.com/nordnet/cordova-universal-links-plugin#path path with multiple wildcard are valid
Example : 
`<path url="*mypath*" />`

But the generated AndroidManifest contains : 
`<data android:pathPattern="/.*mypath*"/>`
(note the missing point before the last wildcard)

I think that line is responsible : 
https://github.com/nordnet/cordova-universal-links-plugin/blob/master/hooks/lib/android/manifestWriter.js#L301

`pathName = pathName.replace('*', '.*');`

It should be :

`pathName = pathName.replace(/\*/g, '.*');`

**Comment by nikDemyankov** [comment]
Thanks, will check it out.
