### ISSUE TITLE
Desire a "Not" feature for a path (BTW We love this plugin - thank you!!!)

### ISSUE THREAD

**Issue by rickmortensen** [nordnet/cordova-universal-links-plugin#30]
We have 1 path that we Don't want to open in our app (especially when we're already in the app).
For ex, we have a link to a "Printable" version of a form, that we want to force the user to open in a browser.  A link to this "Printable" form is within our app, so there might be another way to force the user to open it with a browser (preventing our app from being one of the choices in Android's Open App list).  ios permits this:   "To specify an area that should not be handled as a universal link, add “NOT ” (including a space after the T) to the beginning of the path string.".  Perhaps Android doesn't support it.

**Comment by nikDemyankov** [comment]
Thanks :)

I'm afraid this is iOS-only feature, no such option for Android. In Android you can only define regex for the url, and that's it. Maybe you can play with that, but, probably, you already did that.

I'm afraid you'll either have to change the url of the "Printable" to something totally different, or let the app to be opened, but on the JS side capture that and then open the browser from the app.

But I would say, that changing the "Printable" link on the website is the easiest solution. Or just define more detailed urls in the `<path />` preference.

**Comment by rickmortensen** [comment]
Wow - and fantastic support as well - definitely earned a star - thank you!  I've explicitly listed our paths for now, and hope that Android steps up to the new ios "Not " capability.

**Comment by nikDemyankov** [comment]
Glad to help :)
