### ISSUE TITLE
Not adding intent-filter to activity

### ISSUE THREAD

**Issue by ericman93** [nordnet/cordova-universal-links-plugin#31]
When I'm using the guide everything works fine.
But when I tried to add the plugin to existing project the activity never gets the new intent-filter at the Manifest, and there is no action and data elements no where.

The universal-link part at the config is the same.
What should I do?

**Comment by nikDemyankov** [comment]
That's strange. Is this Android only issue, or similar problem with iOS?

Try to run:

```
cordova clean
cordova prepare
cordova build
```

Sometimes that helps. If not, then you'll have to debug plugin hooks.

Intent-filters are added to the Manifest on the `after_prepare` stage. This is done by the plugins hook, which is: `<YOUR_PROJECT_ROOT>/plugins/cordova-universal-links-plugin/hooks/afterPrepareHook.js`. He checks, if there are any preferences set, and then executes `<YOUR_PROJECT_ROOT>/plugins/cordova-universal-links-plugin/hooks/lib/android/manifestWriter.js`. Try to debug them and see, why nothing is added.

But if it runs fine on a clean project, then the reason, probably, is one of the following:
1. Plugin is not actually added to the project. Maybe some cordova issue.
2. Plugin does his job with the manifest, but it get's rewritten by some other plugin.
3. Plugin can't find Manifest file.
4. Plugin bug :) But for that you'll have to do some digging in the hooks I described, or give me the way to reproduce this.

**Comment by ericman93** [comment]
Nobby question that I could not found the answer to: 
How can I debug plugin hooks?

**Comment by ericman93** [comment]
The problem was that my confiig file was not found.
Mine was inside the _www_ folder and not in the root
