### ISSUE TITLE
html links wont open the app

### ISSUE THREAD

**Issue by ericman93** [nordnet/cordova-universal-links-plugin#32]
My config looks like that

```
<universal-links>
     <host name="timetable.co.il" />
</universal-links>
```

When I'm using _adb shell am start_ the app is opens fine.

But when I'm using 

```
<a href="http://timetable.co.il">open sesame</a>
```

the site is opened in the browser with _www_ prefix and some other path.

Still not worked when I've added another host with _www_ prefix.

**Comment by nikDemyankov** [comment]
If application get's opened with `adb shell am start ...` command - then you configured your app on the native side correctly. Now you need to modify your web side, as described in the [documentation](https://github.com/nordnet/cordova-universal-links-plugin#android-web-integration). If you just press on the link - it will open in the browser by default. In best case - it will ask the user, where he wants to open the link: in the browser or in the app.

**Comment by ericman93** [comment]
I it to ask the user where he wants to open the link.
When I'ved used the the app name as URL_SCHEME it worked fine.
The modification of the web site is beacuse its HTTP URL SCHEME?

**Comment by nikDemyankov** [comment]
Yes, because of that. The idea behind the Universal Links is to use one scheme for everything: both web and mobile. That is why you need to tell, what url's should be opened (if possible) inside the app. And you need to define this on the website and in mobile app.

**Comment by ericman93** [comment]
I've figure it out.
The problem was that when you go to _timetable.co.il_ it will redirect to another route.
But when the value of the **href** was _timetable.co.il/no-route_ and I speficy that route at the config file, it worked fine because there was not routing.

Another solution is to add path with the routing url.
For some reason \* is not working.

**Comment by nikDemyankov** [comment]
My guess the problem is with the redirect. Universal Links doesn't work with them. But as I understand, you fixed the issue?

**Comment by ericman93** [comment]
Yeah thank you
