### ISSUE TITLE
universalLinks empty object

### ISSUE THREAD

**Issue by subpublic** [nordnet/cordova-universal-links-plugin#35]
Hello! My universalLinks seems to be defined, but empty.

If I run
document.addEventListener('deviceready', function() {
          console.log(universalLinks);
}
it logs {}

And if I try do run universalLinks.subscribe(...)
I'm getting a big constrain error.
"Unable to simultaneously satisfy constraints."

I'm using XCode 7.2.
Any ideas?

**Comment by nikDemyankov** [comment]
Hi,

> Unable to simultaneously satisfy constraints.

Usually this means, that there are some problems with the views layout. Mainly - AutoLayout. Plugin is not touching views in any way, so it shouldn't lead to this. Maybe some other plugin? Or maybe problems with Cordova itself. What version you are using?

Also, have you tried UL plugin on the fresh app?

**Comment by subpublic** [comment]
Hi, sorry making a bad issue. The constrain thing actually had nothing to do with this, disappeared when I rebooted the computer.
And universalLinks wasn't actually empty, it was just cordovas console.log that was bad at printing objects. I'll start a new issue with a better headline.
