### ISSUE TITLE
[android] domain name case sensitive?

### ISSUE THREAD

**Issue by TonivdW** [nordnet/cordova-universal-links-plugin#44]
I notice the Universal Links routines in my app are not getting triggered if the incoming url link has the domain name in mixed case.
https://ttapp.nl/info **is** being handled
https://TTapp.nl/info is **not** being handled
The app is started OK with both links, it's just the UL that is not getting fired.
Please advise.

**Comment by nikDemyankov** [comment]
Yes, it is case sensitive. Shouldn't be that hard to improve this.

**Comment by nikDemyankov** [comment]
Fixed in v1.1.1. Version is released.

**Comment by TonivdW** [comment]
I included 1.1.1 in my project and can confirm that this now works, that is, partly...
An mixed-case link from the gmail app correctly opens my app and navigates to the right page.
If I do the same from WhatsApp my  app is foregrounded, but no navigation is taking place.

**Comment by nikDemyankov** [comment]
I think again it depends on the app, from which you are clicking on the link... But does WhatsApp opens your app from this mixed-case link?

**Comment by TonivdW** [comment]
Yes. WhatsApp opens my app, but it is left on the page that was already active if the app was backgrounded. If it is a coldstart then just the startpage appears. If I use an all lowercase link, the navigation does happen.

**Comment by nikDemyankov** [comment]
And it work's fine in the case of gmail... This is so weird... Will try to reproduce it on my phone.

**Comment by TonivdW** [comment]
Yes, correct.
FWIW: my phone is running Android 4.4.4
If I can help by running some logging or testing, please yell.

**Comment by nikDemyankov** [comment]
Thanks, will do :)
