### ISSUE TITLE
Universal link doesnt work on root location

### ISSUE THREAD

**Issue by ivansoldoid90t** [nordnet/cordova-universal-links-plugin#46]
my problem is the following, I had set the apple-app-site-association on my site, and set all necessary configuration to make it work , and it works perfectly , it open the app instantly , but the problem is that only works when the url is not the root

https ...mywebsite.com/test =>works, it goes to the app.

https ...mywebsite.com/anything =>works , goes to the app.

https ...mywebsite.com/ =>doesn't work , goes to the browser.

https ...www.mywebsite.com =>doesn't work , goes to the browser.

https ...mywebsite.com?test=123 =>doesn't work , goes to the browser.

Im using cordova , my config xml includes

```
<host name="www.mywebsite.com" scheme="https" event="launchedAppFromLink"/>
```

my apple-app-site-association

 {
  "applinks": {
    "apps": [],
    "details": [
      {
        "appID": "<ID MEMBER>.com.mywebsite.app",
        "paths": [
          "*"
        ]
      }
    ]
  }
}
The file format , the signature, and everything seems to be fine, thats why its working on non root urls.

Is anybody know how to solve this issue?

**Comment by nikDemyankov** [comment]
Try the following:
1. Delete app from your device.
2. Change `paths` in `apple-app-site-association` file like so:
   
   ```
   "paths": [
           "*", "/"
   ]
   ```
3. Reinstall the app and try again.

**Comment by ivansoldoid90t** [comment]
works great! Thank you very much!

**Comment by nikDemyankov** [comment]
Good :) Closing, then.
