### ISSUE TITLE
Unable to install plugin without root permissions

### ISSUE THREAD

**Issue by sergop321** [nordnet/cordova-universal-links-plugin#48]
Trying to install plugin using cordova cli,
Unable to install npm dependecies without root permissions,
If using root permission, all other operation in cordova cli (build/run) require root permission

Cordova cli version 6.0
Npm version 2.7.3

Error on running: cordova plugins add cordova-universal-links-plugin
Fetching plugin "cordova-universal-links-plugin" via npm
Installing "cordova-universal-links-plugin" for android
Checking dependencies:
    Can't find module mkpath, running npm install
Installing "cordova-universal-links-plugin" for ios
    Failed to install module mkpath:Error: Command failed: /bin/sh -c npm install -D mkpath
npm WARN locking Error: EACCES, open '/Users/Sergo/.npm/_locks/mkpath-2eed79c4f3589c41.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/Sergo/.npm/_locks/mkpath-2eed79c4f3589c41.lock failed { [Error: EACCES, open '/Users/Sergo/.npm/_locks/mkpath-2eed79c4f3589c41.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/Sergo/.npm/_locks/mkpath-2eed79c4f3589c41.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-D" "mkpath"
npm ERR! node v0.12.1
npm ERR! npm  v2.7.3

npm ERR! Attempt to unlock /Users/Sergo/src/oktopost/mobile/board/node_modules/mkpath, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Sergo/src/oktopost/mobile/board/npm-debug.log

**Comment by nikDemyankov** [comment]
You should not need root permissions for that. I'm not running as a root, and it get's installed fine. 

Either way, when plugin is installed - it executes JS hook, that loads additional npm packages (locally), defined in [package.json](https://github.com/nordnet/cordova-universal-links-plugin/blob/master/package.json#L38).  As a workaround you can do the following:
1. Delete plugin from your project:
   
   ```
   cordova plugin remove cordova-universal-links-plugin
   ```
2. Install dependency modules manually inside your project by executing:
   
   ```
   npm install mkpath
   npm install xml2js
   npm install rimraf
   npm install node-version-compare
   npm install plist
   ```
3. Add plugin:
   
   ```
   cordova plugin add cordova-universal-links-plugin
   ```

**Comment by sergop321** [comment]
I did it yesterday as a workaround to make it work,

It probably because installing packages with npm on mac require root privileges, (There several workaround for this).

It is ok if I need to install the npm packages as a root, (for example cordova installation guide:
sudo npm install -g cordova)

The issue that it will require all other operation with cordova cli a root permissions.
I think it might be fixed by updating permission on copied files
