### ISSUE TITLE
scheme="https" not working on android

### ISSUE THREAD

**Issue by Tarekajaj** [nordnet/cordova-universal-links-plugin#49]
even though i am using scheme="https" application only open with http links

I've put this in config.xml

`<universal-links>
        <host name="example.com" scheme="https">
            <path url="/path" event="ul_event" />
        </host>
    </universal-links>`

PS: I have this problem ith v1.0.0 and 1.1.0

**Comment by Tarekajaj** [comment]
it does not seems to be updating the manifest file after making changes in config.xml

**Comment by nikDemyankov** [comment]
That's strange. Just checked it and it works...
1. Created new project
   
   ```
   cordova create UL
   cd ./UL
   cordova platform add android
   cordova plugin add cordova-universal-links-plugin
   ```
2. Opened project's `config.xml` and added:
   
   ```
   <universal-links>
       <host name="example.com" scheme="https">
         <path url="/path" event="ul_event" />
       </host>
     </universal-links>
   ```
3. Run the app:
   
   ```
   cordova run android
   ```
4. Closed the app by pressing back button on the emulator.
5. In the console simulated launch with `http`:
   
   ```
   adb shell am start -W -a android.intent.action.VIEW -d "http://example.com/path" io.cordova.hellocordova
   ```
   
   As a result, got error:
   
   ```
   Starting: Intent { act=android.intent.action.VIEW dat=http://example.com/path pkg=io.cordova.hellocordova }
   Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=http://example.com/path flg=0x10000000 pkg=io.cordova.hellocordova }
   ```
6. When simulated `https`:
   
   ```
   adb shell am start -W -a android.intent.action.VIEW -d "https://example.com/path" io.cordova.hellocordova
   ```
   
   And got positive response with app launched:
   
   ```
   Starting: Intent { act=android.intent.action.VIEW dat=https://example.com/path pkg=io.cordova.hellocordova }
   Status: ok
   Activity: io.cordova.hellocordova/.MainActivity
   ThisTime: 121
   TotalTime: 121
   Complete
   ```

If manifest file is not updated - then the plugin hooks are not executed, when you are running `cordova build`. They are located in `plugins/cordova-universal-links-plugin/hooks` folder. You need a `afterPrepareHook.js`. Try to add logging in it and see, where it breaks.

**Comment by Tarekajaj** [comment]
The problem was an **&** in the description tag in the config.xml file breaking everything. (_WEIRD_).
