### ISSUE TITLE
Array Parameters Not Parsed Properly

### ISSUE THREAD

**Issue by izhekov** [nordnet/cordova-universal-links-plugin#55]
URLs containing array parameters like "dcid[]=1&dcid[]=2&dcid[]=3" are not parsed properly under Android. Those are missing from the event's data "params" property. I did not tested the same under iOS.

**Comment by nikDemyankov** [comment]
Okey, thanks for the info. I think you can get the actual URL from the `url` parameter of the event data, and then read these params from it.

**Comment by izhekov** [comment]
That's exactly what I'm doing. I'm manually parsing the needed parameters at the JS side. I can see the issue is probably related of using the Uri's getQueryParameterNames(). In fact the method probably works just fine as http://www.faqs.org/rfcs/rfc2396.html says those are not allowed:

Other characters are excluded because gateways and other transport agents are known to sometimes modify such characters, or they are used as delimiters.
unwise      = "{" | "}" | "|" | "\" | "^" | "[" | "]" | "`"

Still I believe this pattern is quite commonly used and it will be good if it's supported by your plugin.
