### ISSUE TITLE
Is possible deny a subpath?

### ISSUE THREAD

**Issue by leonardobazico** [nordnet/cordova-universal-links-plugin#57]
Has any way of deny a subpath?

Something like:

``` xml
<universal-links>
    <host name="example.com">
        <path url="/some/path" />
        <path url="!/some/path/subpath" />
    </host>
<!-- or -->
    <host name="example2.com">
        <path url="/some/path" />
        <path url="/some/path/subpath" deny="true" />
    </host>
</universal-links>
```

**Comment by nikDemyankov** [comment]
This question is similar to https://github.com/nordnet/cordova-universal-links-plugin/issues/30 . 

This is possible for iOS, since it does support denying paths. But Android doesn't. So, at the moment, can't add this feature :(

**Comment by leonardobazico** [comment]
@nikDemyankov thank you for the answer.

**Comment by mccooll** [comment]
I manually use the NOT syntax in apple-app-site-association, and for android I just used specific paths (no wildcards).
https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html
