### ISSUE TITLE
Can't build on android after adding the plugin

### ISSUE THREAD

**Issue by Alexintosh** [nordnet/cordova-universal-links-plugin#58]
Error is: 
`No resource identifier found for attribute 'autoVerify' in package 'android'`

Refering to the generated line:
`
<intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:host="host.com" android:scheme="http" android:pathPattern="/path/.*"/>
      </intent-filter>
`

**Comment by nikDemyankov** [comment]
Please, look into [this issue](https://github.com/nordnet/cordova-universal-links-plugin/issues/53) on how to solve yours. In short: try to install the latest android platform in your project.
