### ISSUE TITLE
Can't get it to work on iOS

### ISSUE THREAD

**Issue by jusdeleon** [nordnet/cordova-universal-links-plugin#60]
I tried building my app with Intel XDK. Do I strictly need to build the project on the CLI in order for it to work?

**Comment by nikDemyankov** [comment]
Plugin uses JS hooks to configure native project properly. They are executed when you run `cordova prepare` or `cordova build`. You can build your project without the CLI, but you'll have to configure resulting project manually.

**Comment by jusdeleon** [comment]
Hi, by "configure", are we talking about the `apple-app-site-association` file? Or the configuration of the plugin itself?

**Comment by nikDemyankov** [comment]
Plugin does the following changes in the native project:
1. Enables `Associated Domains`.
2. Generates entitlements file with the list of associated domains. It uses domains, that you defined in `config.xml`.

Also, it generates `apple-app-site-association` file. This file is outside of the native project. Although, it holds domains from the `config.xml`.

If you want to use plugin and can't prepare it from the CLI by executing `cordova prepare` - then you will have to make these steps manually.

**Comment by jusdeleon** [comment]
I'm receiving this error when building in the CLI:

`Code Sign error: No matching provisioning profiles found: None of the valid provisioning profiles allowed the specified entitlements: com.apple.developer.associated-domains.`

Was wondering if you could help me out.

**Comment by nikDemyankov** [comment]
As stated in the error message: you are trying to sign the app with the wrong provisioning profile. Go to your Apple developer console and [check app preferences](https://github.com/nordnet/cordova-universal-links-plugin#activate-ul-support-in-member-center).

Also, check that the bundle id of the app you are building is correct.

**Comment by jusdeleon** [comment]
Thanks for your help. Got it working.

**Comment by nikDemyankov** [comment]
Great :)
