### ISSUE TITLE
App does not open

### ISSUE THREAD

**Issue by sagikarni** [nordnet/cordova-universal-links-plugin#61]
Hello,
Trying to use the plugin in my android device.
I have 
1. installed the plugin
2. Configured the config.xml and added the following: 

`<universal-links>
    <host name="mydomain.com">      
    </host>
/universal-links>`
3. Added the following script on device ready event : 
universalLinks.subscribe(null, function (eventData) {
  // do some work

});

To test is I have set up a web page with the following link element : 
`<a href="http://mydomain.com" target="_blank"> click here </a>`

When clicking the link the app is not opened, instead , the browser opens and direct me to http://mydomain.com ,
Any ideas ?

Thanks
Sagi

**Comment by nikDemyankov** [comment]
Hi,

Have you tried to send an email with this link and open it from the mail on the test device?
