### ISSUE TITLE
Plugin does not handle www.domain.com? [iOS]

### ISSUE THREAD

**Issue by jusdeleon** [nordnet/cordova-universal-links-plugin#64]
I'm testing using slack and when i click on domain.com/path, it gets handled. If I click on www.domain.com/path, it does not open in the app. Any help would be appreciated. Thanks!

**Comment by nikDemyankov** [comment]
Depends on how you defined it in `config.xml` and in `apple-app-site-association-file`. If app is not launched from `www.domain.com/path` - most likely you specified it in configs without www.

**Comment by jusdeleon** [comment]
So if I have this block of host,

```
        <host name="hostname.com">
          ...
        </host>
```

I'll have to define another block for supporting `www`?

```
        <host name="www.hostname.com">
          ...
        </host>
```

If this is the case, how would the site handle two apple-app-association-files?

**Comment by nikDemyankov** [comment]
> I'll have to define another block for supporting www?

Yes.

> how would the site handle two apple-app-association-files?

Hard to say. I'm afraid you will have to experiment with it. I think iOS just takes the domain and appends apple-app-site-association to it and tries to download it from the server. If it fails - it opens browser. If it has some redirects - it also fails.

**Comment by jusdeleon** [comment]
Looks like both is being picked off by the plugin. Defined two hosts and uploaded only one association file since it contains the same contents anyway. Thank you very much.

**Comment by nikDemyankov** [comment]
Great!
