### ISSUE TITLE
Is it working on iOS 8?

### ISSUE THREAD

**Issue by hazem-tamimi** [nordnet/cordova-universal-links-plugin#65]
I've created an app that supports Universal Links on iOS, and I've set all the required configurations. It is working fine on iOS 9, but not on iOS 8.

I've tried it on iOS 8.3 and 8.4.1

Any ideas?

**Comment by nikDemyankov** [comment]
Universal Links are iOS 9+ feature. It's not supported for iOS 8 devices. Plugin will not crash your app on iOS 8 devices, but it's just not gonna do anything in that case, because system API don't support it.

**Comment by hazem-tamimi** [comment]
In this case I guess we should update the Readme file since it is mentioning (under "Supported Platforms") that it is supported...

**Comment by nikDemyankov** [comment]
Updated readme to remove confusion.
