### ISSUE TITLE
 Digital Asset Links

### ISSUE THREAD

**Issue by yernandus** [nordnet/cordova-universal-links-plugin#66]
For android 6 and greater  Digital Asset Links can be used. I wanted to create a pull request but have no permissions.

**Comment by nikDemyankov** [comment]
Cool, thanks! 
You need to create a fork of this repo, add feature in there and then create a PR from the fork to this repo. More info can be found [here](https://help.github.com/articles/using-pull-requests/).

**Comment by nikDemyankov** [comment]
Merged PR. Thanks!
