### ISSUE TITLE
[DOCs] 'Open in app' banners on iOS may not always display

### ISSUE THREAD

**Issue by kristfal** [nordnet/cordova-universal-links-plugin#68]
This is a bug with the iOS 'Open in app' banners, so is not directly related to this plugin, but it should/could be mentioned in the docs to save a lot of hassle for people out there.

In some cases, the 'Open in app' banner may not show in Safari after opening a universal link pointing to a website. The banner will be present on the site, but it 'hides' underneath the URL bar, and thus is invisible to the user. This is consistently reproducible when setting the following CSS styles:

```
body {
      margin: 0;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      position: fixed;
}
```

An example of this issue may be found when opening `maps.google.com` in Mobile Safari. To see the 'Open in app' bar, you'll actually have to drag the search bar or tap at the top of the URL bar (as if you were scrolling to the top of the site).

A fix for this strange behavior is to call `window.scrollTo(0, -100);` when your site has finished loading (or at least painted the body node).

**Comment by nikDemyankov** [comment]
Thanks for the info! Can you do the pull request to the readme file with this data?
