### ISSUE TITLE
[ask] How to works?

### ISSUE THREAD

**Issue by fahmi182** [nordnet/cordova-universal-links-plugin#75]
Hi, i try this plugin to app indexing,

my website structure is, example:

homepage: https://www.example.com
article page: https://www.example.com/articles/example-slug.html

my apps structure is, example:

homepage: /index.html
article page: /detail.html?id=12345

how to connect that with this plugin? sorry i'm noob please help :)
Appreciate!

**Comment by nikDemyankov** [comment]
Hi,

Please, read the [readme](https://github.com/nordnet/cordova-universal-links-plugin) file of this plugin. 

In short, at first you need to set preferences in your application's `config.xml`:

``` xml
<universal-links>
    <host name="www.example.com" scheme="https">
        <path url="/" event="onRootPage" />
        <path url="/articles/*" event="onArticlePage" />
    </host>
</universal-links>
```

Then in JS code:

``` js
var app = {
  // Application Constructor
  initialize: function() {
    this.bindEvents();
  },

  // Bind Event Listeners
  bindEvents: function() {
    document.addEventListener('deviceready', this.onDeviceReady, false);
  },

  // deviceready Event Handler
  onDeviceReady: function() {
    console.log('Device is ready for work');
    universalLinks.subscribe('onRootPage', app.onRootPage);
    universalLinks.subscribe('onArticlePage', app.onArticlePage);
  },

  onArticlePage: function(eventData) {
    console.log('Redirected from articles folder.');
  },

  onRootPage: function(eventData) {
    console.log('Redirected from root page');
  }
};

app.initialize();
```

Also, you need to setup your website as described [here for Android](https://github.com/nordnet/cordova-universal-links-plugin#android-web-integration) and [here for iOS](https://github.com/nordnet/cordova-universal-links-plugin#ios-web-integration).

**Comment by Prasanna-Repo** [comment]
@fahmi182 is the above comment is working ? i have tried and still Chrome android browser unsble to open? @nikDemyankov suggestions please.  

i have completed the below steps 

1 . I have added link tag in website 
     <link rel="alternate" href="android-app://com.learnyst.studio/http/learnandshine.learnyst.com" /> 
2. Verifyed my website on Webmaster Tools
3. Connected my app in the Google Play console

**Comment by nikDemyankov** [comment]
@Prasanna-Repo Does it work, if you use other browser? Or click on the link from the email/some messenger?

Also, you use `adb` tool locally as described in the [docs](https://github.com/nordnet/cordova-universal-links-plugin#testing-ul-for-android-locally) - app is launched?

**Comment by Prasanna-Repo** [comment]
@nikDemyankov i have checked with adb it opens the app but mail or from browser it's not working.

**Comment by nikDemyankov** [comment]
@Prasanna-Repo it should work from chrome browser. But I am more concerned, that it's not opening from the mail. If `adb` test is passed - then the configuration is correct and app can handle the link properly. If you click on the link in the mail on the real device - it, probably, should ask you what application to use for the clicked link: some browser, or your app. If that is not happening - maybe you already clicked `open link in browser` and set this as a default action? That might be the problem.

Try to go to `Settings->Apps->Configure app` and reset default app for browser and opening links.

Also, try to create a new clean test app, configured to work with some fake domain (i.e. `http://my.test.domain.com`). Just build it, verify, that it is launched with `adb` properly. And then check again via email link. You don't need to configure anything on the server side or google play developer console.

**Comment by PrasannaAtLearnyst** [comment]
HI @nikDemyankov  thanks for helping 

"Try to go to `Settings->Apps->Configure app` and reset default app for browser and opening links."

It opened in mail but its not opening in Chrome browser using this from other site '<a href="http://learnandshine.learnyst.com">launch my app</a>'. and '<link rel="alternate" href="android-app://com.learnyst.studio/http/learnandshine.learnyst.com" />' inside head tag of my website. 

Please provide solution

Thanks

**Comment by Prasanna-Repo** [comment]
HI @nikDemyankov  thanks for helping 

"Try to go to `Settings->Apps->Configure app` and reset default app for browser and opening links."

It opened in mail but its not opening in Chrome browser using this from other site `<a href="http://learnandshine.learnyst.com">launch my app</a>`. and `<link rel="alternate" href="android-app://com.learnyst.studio/http/learnandshine.learnyst.com" />` inside head tag of my website. 

It opened the app but not triggering the callback
`universalLinks.subscribe('ul_myExampleEvent', didLaunchAppFromLink);`

`function didLaunchAppFromLink(eventData) {
  alert('Did launch application from the link: ' + eventData.url);
}`

Please provide solution

Thanks

**Comment by nikDemyankov** [comment]
Sorry for the late reply...

So, if I understood correctly - UL works, if you click on the link in email, and event is dispatched properly. But when you click on the link in the Chrome browser - user remain in it.

If email works - then your app has a correct setup. If you don't see app chooser when clicking on the link in mail - then, probably, website is also configured properly.

But if Chrome is holding user inside of it's context - I don't think you can change that. It's like with iOS: in some apps and browser it works, in some - it's not (https://blog.branch.io/ios-9.2-deep-linking-guide-transitioning-to-universal-links). Have you tried other browsers?

**Comment by nikDemyankov** [comment]
Hi @Prasanna-Repo,

No, UL plugin doesn't have app indexing feature. It should be a separate plugin for that.

**Comment by Prasanna-Repo** [comment]
Hi @nikDemyankov 
Sure i'm looking into App Indexing If possible i'll try to make a plugin for app indexing.

**Comment by Prasanna-Repo** [comment]
Hi @nikDemyankov 
How to test app URL is working or not
eg: test this url works - `android-app://com.android.testdeeplink/http/testapp.mydomain.com`

**Comment by nikDemyankov** [comment]
Hi @Prasanna-Repo ,

This url is not for testing. It just should be set in your html on the web site, as stated in the [official documentation](https://developer.android.com/training/app-indexing/enabling-app-indexing.html).

For testing you should use url, that is defined in `config.xml`.

**Comment by Prasanna-Repo** [comment]
@nikDemyankov, 
When you submit app in google search console, they test using `android-app` URL. Please visit Google search console and authorize your app and click Fetch as Google option. You can find there

Thank You
