### ISSUE TITLE
How to redirect?

### ISSUE THREAD

**Issue by fahmi182** [nordnet/cordova-universal-links-plugin#76]
How i redirect after i found detail page in app..

`test {

onNewsDetailedPageRequested: function(eventData) {

```
  var ori_url = eventData.url;
  var base_url = cordova.file.applicationDirectory+'www/';
  var urls = purl(ori_url);
  var file_url = urls.attr('file'); 
  var new_file_url = file_url.substring(0, file_url.lastIndexOf("."));             
  var target_url = 'launch.html?slug=';
  var finished = base_url + target_url + new_file_url;
  // Now i have :  file:///android_asset/www/launch.html?slug=segala-yang-perlu-anda-tahu-tentang-samsung-galaxy-note-7
  alert('Showing after to user details page for some news ' + finished);
  //document.location = finished;   
  // do some work to show detailed page
},
```

`

**Comment by nikDemyankov** [comment]
If you just need to redirect to some page by loading url - you can use:

``` js
window.location = finished;
```

**Comment by fahmi182** [comment]
i try many redirect method just not work, error file not found, the apps just load file same as url original, 
example if i test homepage with adb shell:
- error file not found
  file:///android_asset/www/www.example.com/

**Comment by fahmi182** [comment]
Thanks @nikDemyankov 

I solve the problem, this plugin not support because i using custom scheme url, i wanna ask? are this plugin support custom url scheme? and how to use custom url scheme?

**Comment by nikDemyankov** [comment]
No, it doesn't support custom schemes. The idea of this plugin (and universal links in general) is that you use http/https schemes as for normal links.
