### ISSUE TITLE
Error in iosBeforePrepareHook

### ISSUE THREAD

**Issue by mike-nelson** [nordnet/cordova-universal-links-plugin#77]
I tried to add this plugin and build cordova and it throws an error in the hook script.

undefined is not a function
at getOldProjectName in iosBeforePrepareHook,js:65:27

My project name is "Speaking Email" and it has not changed.

**Comment by lunchbag** [comment]
Looks like your environment doesn't yet support Array.prototype.find. Here's a workaround in iosBeforePrepareHook.js:

```
  var projectFile = null;

  files.forEach(function(fileName) {
    if (path.extname(fileName) === '.xcodeproj') {
      projectFile = fileName
    };
  });
```

**Comment by nikDemyankov** [comment]
@lunchbag is probably correct. @mike-nelson you can either update your version of the node, or use the code snippet from above.

**Comment by sandwichfeet** [comment]
@nikDemyankov  Just confirming I get the same error using node 6.4.3 and 6.5.0.  lunchbag's fix does work correct it though

**Comment by mike-nelson** [comment]
Thanks.  Can this polyfill be committed to the project?

Cheers
Mike

Mike Nelson // CEO (and Developer)
beweb // P 09 3077042 // M 027 4403757
Listen to email safely while driving with www.speaking.email

**Comment by nikDemyankov** [comment]
Will do

**Comment by nikDemyankov** [comment]
Fixed in v.1.2.1.
