### ISSUE TITLE
Link not working from banner page

### ISSUE THREAD

**Issue by anilsaxena** [nordnet/cordova-universal-links-plugin#78]
Universal links working and opening correct page from normal links but when shown in IOS Banner, it is opening the app but app-argument field is not passed. Is there something else needed ?

**Comment by nikDemyankov** [comment]
What do you mean by `app-argument field`? To be honest - can't really test this with banner myself. But you can check, what is happening by opening Xcode and running your app on a device in debug mode. And then set a break point in [AppDelegate+CULPlugin.m on line 21](https://github.com/nordnet/cordova-universal-links-plugin/blob/master/src/ios/AppDelegate%2BCULPlugin.m#L21) and in [CULPlugin.m on line 43](https://github.com/nordnet/cordova-universal-links-plugin/blob/master/src/ios/CULPlugin.m#L43). Then just hit the banner on your device and see, what data app gets.

**Comment by mikew** [comment]
That's in the master branch, version 1.2.2 hasn't been released. Is there any timeline for that?
