### ISSUE TITLE
Warning during build on iOS breaking universal-links

### ISSUE THREAD

**Issue by rolinger** [nordnet/cordova-universal-links-plugin#79]
During the "cordova build iOS" as well as in Xcode's "build to simulator/device" I am getting the following errors:

`warning: no rule to process file '/Users/test/dev/myApp/platforms/ios/myApp/Plugins/cordova-universal-links-plugin/Model/CULHost.h' of type sourcecode.c.h for architecture x86_64
warning: no rule to process file '/Users/test/dev/myApp/platforms/ios/myApp/Plugins/cordova-universal-links-plugin/Model/CULPath.h' of type sourcecode.c.h for architecture x86_64
warning: no rule to process file '/Users/test/dev/myApp/platforms/ios/myApp/Plugins/cordova-universal-links-plugin/Parser/CULXmlTags.h' of type sourcecode.c.h for architecture x86_64
warning: no rule to process file '/Users/test/dev/myApp/platforms/ios/myApp/Plugins/cordova-universal-links-plugin/Parser/CULConfigXmlParser.h' of type sourcecode.c.h for architecture x86_64
warning: no rule to process file '/Users/test/dev/myApp/platforms/ios/myApp/Plugins/cordova-universal-links-plugin/Utils/NSBundle+CULPlugin.h' of type sourcecode.c.h for architecture x86_64`

**Comment by nikDemyankov** [comment]
Usually this warning is because of some misconfiguration in the project: header files are added to the build phase. Cordova itself is responsible for setting up the project. So I would suggest to try one of the following:
1. Remove and then add ios platform. And try to build again.
2. Clean up the project: first try from the console, then from xcode.
3. In Xcode go to Build Phases tab and remove these headers from it.

**Comment by jpduckwo** [comment]
I also have this problem recurring whenever I regenerate the cordova project, I don't get any other problems like this for other plugins and I'm using 8. Is there something that can be changed in the plugin to handle this better?

**Comment by nikDemyankov** [comment]
Found what causing it. Will fix that.

**Comment by nikDemyankov** [comment]
Fixed in repo, will release new version a bit later.

**Comment by rolinger** [comment]
good to know.  I had to remove the plugin from my ios build.  once updated I will load it again into my ios project.  Thanks

**Comment by nikDemyankov** [comment]
Released v1.2.1. Should be fixed.
