### ISSUE TITLE
Shorten Url redirects to Safari

### ISSUE THREAD

**Issue by DeepikaKochar** [nordnet/cordova-universal-links-plugin#80]
If I use shorten url then it opens safari first with smart banner when pulled down.

**Comment by nikDemyankov** [comment]
Both iOS and Android supports only links, that are defined in the configs. And if shorten url is not in there - it will be opened in the browser. This is how Universal Links work on both platforms, and it's not controlled by the plugin.

**Comment by DeepikaKochar** [comment]
oh.. thank you so much. I'll try it.

**Comment by nikDemyankov** [comment]
you're welcome :)
