### ISSUE TITLE
Support for Host Port

### ISSUE THREAD

**Issue by szh** [nordnet/cordova-universal-links-plugin#81]
If I want my app to handle URLs with a custom port, the `<intent-filter>` in the AndroidManifest.xml should look like this:
`<data android:host="foo.bar" android:port="1234" />`
Currently, there doesn't seem to be a way to specify a port in the config.xml file though. If I add the port to the `host` property: `<host name="foo.bar:1234">` then the port is copied as is into the AndroidManifest.xml's `android:host` property, and the intent doesn't function. If I write `<host name="foo.bar" port="1234">` then it's completely ignored.

Any plans to support this?

**Comment by nikDemyankov** [comment]
Sure, this can be added. Although, don't think that iOS supports this, so it's gonna be an Android-only feature... But why not.

**Comment by newuser44** [comment]
Did this get added?  
Just new to the whole cordova stuff and we were trying to add this in our app.  Trying to prove that it can work with just a local server (which has a port).  As far as I can tell this is the one thing that is holding it up from working.
