### ISSUE TITLE
Workaround needed for PGB

### ISSUE THREAD

**Issue by kimras** [nordnet/cordova-universal-links-plugin#82]
Hi
I know that it has been discussed in thepast, but I am really in a big pile of poo at the moment after the security update for iOS removed the url_schema entirely in 9.3.4 .. I know it was announced but ...

Anyway, My setup is a Windows dev. and iOS, Android + WP8 build on Phonegap build.. so I am on the hunt for a solution that will work with Phonegap Build without a xcode implementation, specifically on iOS, It looks like it is a problem with the entitlement file. i have been at it all weekend but so fare been unsuccessful. 

Any help od hint on this will be highly appreciated.

Thanks in advance
Kim

**Comment by nikDemyankov** [comment]
I don't think you can use this plugin with PGB. The main reason is that PGB doesn't support custom attributes in the `config.xml`. And they are used during `cordova prepare` phase and when app is running.

Plus you need to include in the project entitlements file. You can create it manually, but I'm not sure, that you can include it properly in the native project via PGB: don't think that it has that feature... Sorry.

**Comment by granicz** [comment]
(Arrived here from Google, thanks guys for this marker ticket.)

@nikDemyankov Can you give a bit more info, what custom attributes are needed and have you raised this with the PGB team?  I am not sure I see how those custom attributes are/can be used "when the app is running."  Could you please elaborate?

**Comment by nikDemyankov** [comment]
@granicz you can check out thread https://github.com/nordnet/cordova-universal-links-plugin/issues/28 , there's a big discussion regarding PGB.
