### ISSUE TITLE
Can we exclude `path` in url matching?

### ISSUE THREAD

**Issue by zhaohanweng** [nordnet/cordova-universal-links-plugin#87]
I want to match all path under the domain except for a few path. i.e. `example.com/unsubscribe.html`

Is there a way to do this?

**Comment by nikDemyankov** [comment]
In the case of iOS you can do that manually as described in [official iOS documentation](https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html):

> To specify an area that should not be handled as a universal link, add “NOT ” (including a space after the T) to the beginning of the path string. For example, the apple-app-site-association file shown in Listing 6-1 could prevent the /videos/wwdc/2010/\* area of the website from being handled as a universal link by updating the paths array as shown here:
> 
> "paths": [ "/wwdc/news/", "NOT /videos/wwdc/2010/_", "/videos/wwdc/201?/_"]

Android doesn't have that feature, so you can't. 

As kind of a workaround you can allow app to capture them all, and if some link should not be handled by the app - use in-app browser plugin to display that page.

**Comment by zhaohanweng** [comment]
Thanks. I guess I ll have to use the work around for android.
