### ISSUE TITLE
app verification not triggered state is undefined

### ISSUE THREAD

**Issue by slootmaekersdirk** [nordnet/cordova-universal-links-plugin#88]
hello,

I provisioned everything as the document stated. The adb check with the activity localy works fine (it opens the app without a chooser dialog). the issue is that I still get the 'open with' (when i use a link in an sms message) dialog box (android 6) event when I have added the assetlinks.json file (and verified it with the check url https://digitalassetlinks.googleapis.com/v1/statements:list?source.web.site=https://applogicdev.idealsystems.be&relation=delegate_permission/common.handle_all_urls)

when I do a adb shell dumpsys package d the status = undefined. Also in the log cat I cannot see an entry that is verifying this (should be something like ACTION_INTENT_FILTER_NEEDS_VERIFICATION)

my intent filter is looking like this:

``` xml
 <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:host="applogicdev.idealsystems.be" android:scheme="https"/>
      </intent-filter>
```

can you assist or point what the issue is?

**Comment by slootmaekersdirk** [comment]
just for the record, the status is not undefined, but ask -> hence the open with appears. the question is how can I debug this?

Dirk

**Comment by nikDemyankov** [comment]
Hi,

Sorry, but not sure I can be much of the help in here :( Can suggest only to double check everything, as described in [here](https://developer.android.com/training/app-links/index.html), maybe [here](https://developer.android.com/training/app-indexing/enabling-app-indexing.html)...

**Comment by nikDemyankov** [comment]
Also, not sure that you can debug the app itself. The problem is that app is not alive until user selects with which app he wants to open the link.

But you can open `PROJECT_NAME/platforms/android` in Android Studio and run the app from it on the real device (not emulator). Then try to open a link from it. But again, it's not gonna be launched until user choose it.

**Comment by tngcanh07** [comment]
Hi,
It seems it only works with the build from Play Store. When I install the application from Android Studio, also get the same problem.

**Comment by sjahan** [comment]
Hi, 

I'm encountering the same problem... Can you confirm it will only work with a build delivered by the Play Store? As the `assetlinks.json` file mentions the certificate, I assumed I had to sign the APK as if I was going to publish it on the store, but even with the signed version with the production certificate, I always get the disambiguation popup.

It feels quite annoying that it is not possible to test this before publishing it... :(

**Comment by TianleZhang** [comment]
Hi,

I am also faceing the face problem. And it even happened to the app from Play store. I have go through the tutorial several times already, and after the install, the status of the app is always `ask`
