### ISSUE TITLE
Move entitlements hook logic to plugin.xml

### ISSUE THREAD

**Issue by alexbuijs** [nordnet/cordova-universal-links-plugin#89]
In the upcoming cordova-ios 4.3.0 the entitlements can be configured through plugin.xml. See: https://issues.apache.org/jira/browse/CB-11854. This could be a replacement for the ios hooks for adding the entitlements.

**Comment by nikDemyankov** [comment]
Cool, thanks for the info! Although, I think entitlement hooks will remain for some time, since not everyone will upgrade to 4.3. I know some people, who are still using v3 for different reasons.

**Comment by dorgold** [comment]
This is not really an enhancement, this plugin is now **broken** in cordova-ios 4.3.0 and above.

Cordova now uses build.xcconfig to set: 
```CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist```

This overrides the entitlements file set by this plugin, and associated domains are not appearing in the new Entitlements-Debug.plist / Entitlements-Release.plist

**Comment by chancezeus** [comment]
For those in need, I did a "quick and dirty"/"it works for me" fix of the generation of the entitlements based on the newer cordova versions (Entitlements-[Debug/Release].plist). I do not currently have the time to make a more "code style" and/or backwards compatible fix but please see: chancezeus/cordova-universal-links-plugin@9e313aa63d13fbdc91c3a10d17f006f5367dcf90

**Comment by mark-veenstra** [comment]
https://github.com/Mediapioniers/cordova-universal-links-plugin/tree/refactor-hooks-for-cli-builds?files=1
