### ISSUE TITLE
<universal-links> tag is not set in the config.xml

### ISSUE THREAD

**Issue by Flomaz** [nordnet/cordova-universal-links-plugin#91]
Hello

Thank you for your work. I was looking for a way to make deep links in my app and when i found this plugin i was relieved.
But i have a problem and maybe someone could have an idea ?

I put the UL tag in my config.xml : 
`<universal-links>
    <host name="myhostname" scheme="https" event="eventData">
    </host>
</universal-links>`

The local build for Android is always successful, but at the end i have the following error : 

> <universal-links> tag is not set in the config.xml. Universal Links plugin is not going to work.

I tried with cordova 5.0.0 and cordova 5.4.1

any ideas of what's going on ?

Thank you

**Comment by nikDemyankov** [comment]
Hi,

Can you share your `config.xml`? Maybe on some fresh test project, where you can reproduce that issue.

**Comment by angryanatole** [comment]
I had the same issue when I accidentally added tag in the wrong config.xml.
There are usually two config.xml files, one is inside the "www" folder, and the other is on the same level with the folder.
Try adding that tag in the config.xml, not the www/config.xml.
Hope it helps!

**Comment by aantonello** [comment]
Someone has solved this problem? I'm using Cordova CLI version 7.1.0 and getting the same problema when running "cordova prepare android".

**Comment by donvie** [comment]
I have a problem also in cordova 7.0.0
