### ISSUE TITLE
universal links not able to listen to url for ios

### ISSUE THREAD

**Issue by divyachandraprakash** [nordnet/cordova-universal-links-plugin#92]
1. I registered a domain via branch io which is of the form: "xxxx.test-app.link".
2. The root of this domain has apple-app-site-association file("xxxx.test-app.link/apple-app-site-association"), which contains the correct bundle id, path, etc.
3. Correct entries are added in config.xml.
   4.Entitlement for the domain is added, hence on clicking of url with the above mentioned domain, app opening is triggered.
4. Unfortunately, universallinks.subscribe is not able to listen to this url for ios, however it is able to do so for android.

**Comment by nikDemyankov** [comment]
What plugins you are using in the project? And is it Cordova or Ionic project?

**Comment by divyachandraprakash** [comment]
plugins in the project:
 "cordovaPlugins": [
    "ionic-plugin-keyboard@2.2.0",
    "cordova-universal-links-plugin@1.2.0",
    "cordova-plugin-whitelist@1.2.2",
    "cordova-plugin-file@4.2.0",
    "cordova-plugin-statusbar@2.1.0",
    "cordova-plugin-splashscreen@3.2.2",
    "cordova-plugin-inappbrowser@1.4.0",
    "cordova-plugin-network-information@1.2.0",
    "cmt-cordova-plugin-webintent@1.0.0-cmt",
   "cmt-cordova-plugin-clipboard@0.1.0-cmt",
    "com.amadeus.plugin.PreferencesPlugin@1.0.2",
    "cordova-plugin-dialogs@1.2.0",
    "cordova-plugin-secure-storage@2.2.6-cmt2",
    "cordova-plugin-geolocation@1.0.0",
    "cordova-plugin-calendar@4.5.3",
    "cordova-plugin-x-socialsharing@5.1.1"]

**Comment by dcz-switcher** [comment]
Hello, 

I had a similar issue and it came from config.xml, I had forgot scheme="https" 

may be the same with you ?

**Comment by nikDemyankov** [comment]
@divyachandraprakash sorry for the late reply...

I wanted to know what plugins you are using in order to check, that none of them is overriding one specific AppDelegate method. Seems like they are not doing that.

If app is launched - then configuration is correct. If event is triggered on Android - then the JS side also should be fine. 

Try to open `platforms/ios/YOUR_PROJECT_NAME.xcodeproj` file in Xcode and launch app from it on your test device. In the Xcode find `AppDelegate+CULPlugin.m` and set a breakpoint on [line 24](https://github.com/nordnet/cordova-universal-links-plugin/blob/master/src/ios/AppDelegate%2BCULPlugin.m#L24). Then click on the link and see, if it's got triggered.

Also, you can set a breakpoint in `CULPlugin.m` on [line 119](https://github.com/nordnet/cordova-universal-links-plugin/blob/master/src/ios/CULPlugin.m#L119). And check, what is send to the JS side.

**Comment by amovsesy** [comment]
@nikDemyankov, we are having the same issue. The universal link opens the app, but the event is never fired. It works fine on Android, and used to work on iOS, but for some reason it stopped working. I put breakpoints in both the lines you stated above and they never get hit. I also placed break points at line 115 in CULPlugin.m and line 19 in AppDelegate+CULPlugin.m. Line 115 in CULPlugin.m was triggered when the app initially loaded, but when I clicked on a link to go into the app no breakpoints were triggered at all.

List of plugins:
com.wodify.cordova.plugin.instabug 0.0.1 "Cordova-Plugin-Instabug"
cordova-fabric-plugin 1.0.8 "cordova-fabric-plugin"
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-contacts 2.2.0 "Contacts"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.7.1 "Facebook Connect"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-transfer 1.6.0 "File Transfer"
cordova-plugin-google-analytics 1.6.0 "Google Universal Analytics Plugin"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-media-capture 1.4.0 "Capture"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova-sqlite-storage 1.4.8 "Cordova sqlite storage plugin"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
es6-promise-plugin 3.0.2 "Promise"
io.branch.sdk 2.4.2 "branch-cordova-sdk"
ionic-plugin-deeplinks 1.0.8 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
me.tonny.cordova.plugins.multidex 0.1.0 "Cordova Multi Dex"
phonegap-plugin-push 1.8.4 "PushPlugin"

**Comment by mowaiskalam** [comment]
@nikDemyankov same issue for me that is closed

**Comment by artuska** [comment]
I have the same issue for iOS.

When i click on my https link (inside the Gmail app) Android asks me if i want to open it with my app (or with Chrome as the second option) and i choose my app and press «Always» — so, everything works just fine on Android.

But iOS just does not work.

And of course i have all `cordova/config.xml` set up and i have `apple-app-site-association` available by direct link.
