### ISSUE TITLE
Xcode 8 Warning on build for IOS

### ISSUE THREAD

**Issue by jpduckwo** [nordnet/cordova-universal-links-plugin#93]
The following warnings are now appearing when building with Xcode 8. Using plugin version 1.2.0.

```
...Plugins/cordova-universal-links-plugin/AppDelegate+CULPlugin.h:15:36: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
...Plugins/cordova-universal-links-plugin/AppDelegate+CULPlugin.h:15:128: Block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
```

**Comment by divyachandraprakash** [comment]
Inspite of these warnings, do universal links work for ios for you(whether you are able to listen to the incoming url?)

**Comment by jpduckwo** [comment]
Yes but the way they work in IOS is pretty average, e.g. safari only asks you if you want to open the link in the app, it doesn't automatically just open the app which is what I was expecting.

**Comment by nikDemyankov** [comment]
These warnings are not critical, but yeah - I should fix them. But they are not causing the behaviour you are experiencing. 

Maybe there is some misconfiguration with `apple-app-site-association` file? Check [this documentation](https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html), mainly - `Creating and Uploading the Association File` section. You can try to put it in `https://<domain>/.well-known/apple-app-site-association`.

**Comment by nikDemyankov** [comment]
Released v.1.2.1. Closing this one, since it's about warnings in build process. For other problems, please, create a separate issue.
