### ISSUE TITLE
Unable to download app

### ISSUE THREAD

**Issue by vomchik** [nordnet/cordova-universal-links-plugin#94]
After install plugin i got message "Unable to download app". 
Do you have any idea?

![img_0389](https://cloud.githubusercontent.com/assets/732085/20711653/70e4fa72-b649-11e6-8139-c94958df0d65.PNG)

**Comment by nikDemyankov** [comment]
Not sure that plugin has something to do with that... Since you've closed the issue - what was it?

**Comment by vomchik** [comment]
It was problem with my Provision Profile)

**Comment by nikDemyankov** [comment]
Cool, thanks :)
