### ISSUE TITLE
Does this plugin's deep link survive on app installation process?

### ISSUE THREAD

**Issue by skyprimer** [nordnet/cordova-universal-links-plugin#97]
I've installed the plugin without any problem. I can redirect user to any page on app. My question is if it is possible to get the variables after app installation process from itunes somehow.. I know firebase can do that i wonder if this plugin can?

**Comment by nikDemyankov** [comment]
Can you, please, give a small example on how you want the plugin to behave and in what situation? Don't really understand the question...

**Comment by skyprimer** [comment]
Let me tell what firebase does. When you click the universal link and if the app is not installed it takes you to itunes page by your app-id. When the installation process is finished and opened the app the link variable was there to fetch..

I think they are getting fingerprint somehow and then matching it later i dont know i was wondering the process.. This video explains what i mean (first 30 seconds) https://www.youtube.com/watch?v=sFPo296OQqk&t=27s

**Comment by evyatar** [comment]
Look for "deferred deep linking"

**Comment by nikDemyankov** [comment]
Thanks for explanation. No, I don't think plugin does that. When user clicks on a link in the browser and app is launched - it receives a special event with link information. But if you are navigated to the Store (App Store or Google Play), install the app and then launch it from there or later on from the apps list - it should start as usual without any events. So you don't get an original link. But anyways, if user has installed your app - that's a win anyways :)

**Comment by amovsesy** [comment]
@skyprimer take a look at https://branch.io/. We use them to do what you want.

**Comment by adityasaxena** [comment]
@amovsesy Hi there! would it be possible for you to give me a little guidance on how to use branch.io effectively? I'm having a tough time integrating deeplinks on my test distributions on iOS

**Comment by amovsesy** [comment]
@adityasaxena take a look at https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking. The way we do it is to create links that map to places within our app. Then based on the params we route to the correct place.
