### ISSUE TITLE
universalLinks is undefined in IOS

### ISSUE THREAD

**Issue by mowaiskalam** [nordnet/cordova-universal-links-plugin#98]
universalLinks.subscribe is not registering in IOS, i am working on Visual Studio Cordova. Plugin is working fine in android but in IOS it is opening app but not registering events. Please let me know what am i doing wrong ?

**Comment by nikDemyankov** [comment]
Since you've closed the issue - my guess you've solved it. What was the problem, if it's not a secret?)

**Comment by mowaiskalam** [comment]
@nikDemyankov i don't know i should share this or not this would be my problem but i am unable to registered this universalLinks.subscribe in IOS. I am working on windows so i have read all your phonegap build discussion. But i have MAC OS also and i have installed this plugin in MAC too, still unable to register my deep paths because i saw after debugging that universalLinks is undefined on my side. So i guess plugin is not installed properly i don't know why because i am unable to see any error. It will helpful for me if you can do anything into it. Thank you

**Comment by mowaiskalam** [comment]
@nikDemyankov same issue is opened here #92

**Comment by nikDemyankov** [comment]
If `universalLinks` is undefined on your side (JS, I guess) - then there is definitely some installation issue. So I would suggest you to do it from scratch on en empty project via console.

Try to create a new project via console, add this plugin, set it up and see if it will work. Just to eliminate two factors:
- some other plugin is in conflict with UL.
- VS is not installing plugin as it should.
