### ISSUE TITLE
Any plan of supporting custom url schemes?

### ISSUE THREAD

**Issue by mkj-git** [nordnet/cordova-universal-links-plugin#99]
I saw that it might be supported in future. So is this possible in near future release?

**Comment by nikDemyankov** [comment]
Not in the plans right now, sorry...

**Comment by jacquesdev** [comment]
@mkj-git - custom url schemes are on their way out https://blog.branch.io/ios-9-2-redirection-update-uri-scheme-and-universal-links/

**Comment by SailingSteve** [comment]
That branch blog is about ios.  Custom schemes are still needed in Android.
